# -*- coding: utf-8 -*-
"""Aula_1_Operadores_Aritmeticos_Relacionais_e_Logicos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/storopoli/ciencia-de-dados/blob/master/notebooks/Aula_1_Operadores_Aritmeticos_Relacionais_e_Logicos.ipynb

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/storopoli/ciencia-de-dados/master?filepath=notebooks%2FAula_1_Operadores_Aritmeticos_Relacionais_e_Logicos.ipynb)
<br>
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/storopoli/ciencia-de-dados/blob/master/notebooks/Aula_1_Operadores_Aritmeticos_Relacionais_e_Logicos.ipynb)

# Operadores Aritméticos, Relacionais e Lógicos

**Objetivos**: Apresentar variáveis, operadores aritméticos, relacionais e lógicos utilizados em Python.

Documentação Python 3: https://docs.python.org/3/library/index.html

## Variáveis

Uma variável reserva espaço de memória para armazenar um certo tipo de dado e
relacionado a um nome para referenciar o seu conteúdo (nome da variável).

3 tipos básicos:
* Numérico
* Texto (String)
* Lógico (Booleano)

### Variáveis Numéricas

Podem ser de dois tipos:
* `int`: número inteiro
* `float`: número real (ponto flutuante)
"""

# isto é um comentário
x = 10
y = 8.9

print(type(x))
print(type(y))

"""### Variáveis de Texto (`string`)

Qualquer texto é uma `string`
"""

universidade = 'UNINOVE'
logo = 'uni9 é 10'
professor = 'José Eduardo Storopoli'

print(type(logo))
print('Número de caracteres do logo: ', len(logo)) # usando ,
print('Bem-vindo à ' + universidade +
      ', o seu professor é ' + professor) # usando +

"""### Variáveis Lógicas (`bool`)

* Verdadeiro = `True` = $1$
* Falso = `False` = $0$
"""

mortalidade = True

print(mortalidade)
print(type(mortalidade))

"""## Leitura de Dados do Teclado

A função utilizada para efetuar a leitura de dados a partir do teclado é a função `input()`.
"""

print("dados do aluno")
nome = input("informe seu nome: ")
idade = input ("informe sua idade: ")
print (nome, "você tem", idade, "anos!!")

"""## Operadores Aritméticos

* Soma `x + y`
* Subtração `x - y`
* Multiplicação `x * y`
* Divisão `x / y`
* Divisão desconsiderando a parte fracionária `x // y`
* Resto de uma divisão `x % y`
* Absoluto `abs(x)`
* Converter para Inteiro `int(x)`
* Converter para Real `float(x)`
* Potência `x ** y`
"""

x = 10
y = 3

print('Soma: ', x + y)
print('Subtração: ', x - y)
print('Multiplicação: ', x * y)
print('Divisão: ', x / y)
print('Divisão desconsiderando a parte fracionária: ', x // y)
print('Módulo - Resto de uma divisão: ', x % y)
print('x elevado à y potência: ', x ** y)

"""### Arredondamento, Piso e Teto"""

import math
#import math as m 
#from math import floor, ceil

print('round: ', round(3.33))
print('floor: ', math.floor(3.33))
print('ceil: ', math.ceil(3.33))

"""## Operadores Relacionais

Uma condição é o estabelecimento de uma relação lógica entre dois elementos. Para definir uma relação lógica é necessário usar operadores relacionais. Uma relação lógica (comparação) retorna somente os valores verdadeiro ou falso.

* Igual a: `x == y`
* Maior que: `x > y`
* Menor que: `x < y`
* Maior ou igual a: `x >= y`
* Menor ou igual a: `x <= y`
* Diferente de: `x != y`
"""

x = 3
y = 4


print('Igual a: ', x == y)
print('Maior que: ', x > y)
print('Menor que: ', x < y)
print('Maior ou igual a: ', x >= y)
print('Menor ou igual a: ', x <= y)
print('Diferente de: ', x != y)

"""## Operadores Lógicos
São utilizados para uma mesma tomada de decisão que necessite de mais de uma condição. Também são conhecidos como operadores booleanos. Operadores lógicos retornam somente os valores verdadeiro ou falso.

| Operador Lógico | Função    | Prioridade |
|-----------------|-----------|---------------------|
| `NOT`           | Negação   | 1                   |
| `AND`           | Conjunção | 2                   |
| `OR`            | Disjunção | 3                   |
"""

x = 1
y = 3
z = 5
w = 2

print(z > w and w > y)  # False
print(z > w or w > y)   # True
print(not y + w == z)   # False