# -*- coding: utf-8 -*-
"""Aula_0_Jupyter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/storopoli/ciencia-de-dados/blob/master/notebooks/Aula_0_Jupyter.ipynb

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/storopoli/ciencia-de-dados/master?filepath=notebooks%2FAula_0_Jupyter.ipynb)
<br>
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/storopoli/ciencia-de-dados/blob/master/notebooks/Aula_0_Jupyter.ipynb)

# Jupyter

**Objetivo**: Apresentar o ambiente Jupyter Notebook.

Documentação Jupyter Notebook: https://jupyter-notebook.readthedocs.io/en/stable/

## Arquivo

Notebooks são documentos `JSON` com extensão `.ipynb` (**iPy**thon **N**ote**b**ook) 

Trabalha com células:
* Código
* Markdown

### Salvando Notebooks

* `.html`
* `.md`
* `.ipynb`
* `.py`

## Comandos de Células

* Para rodar a célula aperte `Shift + Enter`
* Modo Comando `Esc`
* Modo Edição `Enter`
* Para inserir nova célula aperte `a` (para **antes** da célula selecionada) ou `b` (para **depois** da célula selecionada)
* Para deletar célula aperte duas vezes `d` (delete)
* Copiar célula(s) selecionada(s) aperte `c` (copy)
* Colar célula(s) copiada(s) aperte `v` (paste)
* Mudar tipo:
    * Code `y`
    * Markdown `m`

### Célula de Código
"""

# Isto é uma celula de código

print('Quantos cocos carrega uma andorinha?')

"""### Célula Markdown

Veja documentação em: https://www.markdownguide.org/cheat-sheet/

* LaTeX com entre dólar ( \\$ ): $P(A|B) = \frac{P(B|A) P(A)}{P(B)}$
* Código entre (\```)
```python
print('Qual a velocidade de voo de uma andorinha sem carga?')
```

## Comandos `shell` 

Use o *bang* `!`
"""

!ls

# print working directory
!pwd

"""## Jupyter Magic

Tem [diversos](https://ipython.readthedocs.io/en/stable/interactive/magics.html), mas o que eu mais uso são:

* `%timeit`: Cronometra o tempo de execução de uma **expressão** `Python`
* `%%timeit`: Cronometra o tempo de execução de uma **célula**
"""

# Commented out IPython magic to ensure Python compatibility.
# %timeit 3**999999

# Commented out IPython magic to ensure Python compatibility.
# %%timeit
# x = 3**999999